# Generated by Django 5.1.2 on 2024-10-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_product_create_at_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/product-default.png', null=True, upload_to='images/'),
        ),
    ]
